### ISSUE TITLE
Besty_boy

### ISSUE THREAD

**Issue by Bestyboy** [itsP33t/Say-Discord-Bot#1]

**Comment by itsP33t** [comment]
What is your issue?

**Comment by Bestyboy** [comment]
Hello, I'm really sorry, I made a false manipulation on purpose and sent you a request, really sorry for the inconvenience.
Sincerly

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Peter ***@***.***>
Envoyé : Saturday, September 10, 2022 5:55:15 PM
À : itsP33t/Say-Discord-Bot ***@***.***>
Cc : Bestyboy ***@***.***>; Author ***@***.***>
Objet : Re: [itsP33t/Say-Discord-Bot] Besty_boy (Issue #1)


What is your issue?
